Update generate dump patch
Signed-off-by: arheneus <arheneus@marvell.com>

diff --git a/files/sonic_generate_dump.patch b/files/sonic_generate_dump.patch
--- a/files/sonic_generate_dump.patch
+++ b/files/sonic_generate_dump.patch
@@ -1,5 +1,5 @@
 diff --git a/scripts/generate_dump b/scripts/generate_dump
-index 01e45f8..45a7a84 100755
+index 01e45f8..390c7b7 100755
 --- a/scripts/generate_dump
 +++ b/scripts/generate_dump
 @@ -182,7 +182,7 @@ save_nat_info() {
@@ -15,16 +15,46 @@ index 01e45f8..45a7a84 100755
          fi
      done
  
--    # run 'hw-management-generate-dump.sh' script and save the result file
--    /usr/bin/hw-management-generate-dump.sh
--    save_file "/tmp/hw-mgmt-dump*" "hw-mgmt" false
--    rm -f /tmp/hw-mgmt-dump*
 +    if [[ "$asic" = "mellanox" ]]; then
-+        # run 'hw-management-generate-dump.sh' script and save the result file
-+        /usr/bin/hw-management-generate-dump.sh
-+        save_file "/tmp/hw-mgmt-dump*" "hw-mgmt" false
-+        rm -f /tmp/hw-mgmt-dump*
+     # run 'hw-management-generate-dump.sh' script and save the result file
+     /usr/bin/hw-management-generate-dump.sh
+     save_file "/tmp/hw-mgmt-dump*" "hw-mgmt" false
+     rm -f /tmp/hw-mgmt-dump*
 +    fi
  
      # clean up working tar dir before compressing
      $RM $V -rf $TARDIR
+diff --git a/scripts/generate_dump b/scripts/generate_dump
+index 390c7b7..ef7db50 100755
+--- a/scripts/generate_dump
++++ b/scripts/generate_dump
+@@ -182,7 +182,7 @@ save_nat_info() {
+ save_proc() {
+     local procfiles="$@"
+     $MKDIR $V -p $TARDIR/proc \
+-        && (for f in $procfiles; do $CP $V -r $f $TARDIR/proc || echo "$f not found" > $TARDIR/$f; done) \
++	    && (for f in $procfiles; do ( [ -e $f ] && $CP $V -r $f $TARDIR/proc ) || echo "$f not found" > $TARDIR/$f; done) \
+         && $TAR $V -rhf $TARFILE -C $DUMPDIR --mode=+rw $BASE/proc \
+         && $RM $V -rf $TARDIR/proc
+ }
+@@ -461,7 +461,7 @@ main() {
+     $MKDIR $V -p $LOGDIR
+     $LN $V -s /etc $TARDIR/etc
+ 
+-    ($TAR $V -rhf $TARFILE -C $DUMPDIR --mode=+rw \
++    ($TAR $V -rf $TARFILE -C $DUMPDIR --mode=+rw \
+         --exclude="etc/alternatives" \
+         --exclude="*/etc/passwd*" \
+         --exclude="*/etc/shadow*" \
+@@ -506,7 +506,7 @@ main() {
+     done
+ 
+     # archive kernel dump files
+-    for file in $(find_files "/var/crash/"); do
++    [ -e /var/crash/ ] && for file in $(find_files "/var/crash/"); do
+         # don't gzip already-gzipped dmesg files :)
+         if [ ! ${file} = "/var/crash/kexec_cmd" -a ! ${file} = "/var/crash/export" ]; then
+             if [[ ${file} == *"kdump."* ]]; then
+-- 
+2.17.1
+
